/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Producto;

import Empleados.FmListadoBDDEmpleados;
import Empleados.FmiEmpleados;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FmProductos
     */
    Connection com = null;
    public FmProductos() {
        initComponents();
         try {
            com=DriverManager.getConnection("jdbc:derby://localhost:1527/BDD_CeluTec","william","1234");
        } catch (SQLException ex) {
            Logger.getLogger(FmListadoBDDEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboResolucion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboColor = new javax.swing.JComboBox<>();
        cboMemoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboSistemaOperativo = new javax.swing.JComboBox<>();
        cboMarca = new javax.swing.JComboBox<>();
        txtModelo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setIconifiable(true);
        setTitle("Registro Producto");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/celu.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Celular");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Marca:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Modelo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setText("Memoria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        cboResolucion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboResolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "4.0 pixeles", "4.1 pixeles", "4.2 pixeles", "4.3 pixeles", "4.4 pixeles", "4.5 pixeles", "4.6 pixeles", "4.7 pixeles", "4.8 pixeles", "4.9 pixeles", "5.0 pixeles", "5.1 pixeles", "5.2 pixeles", "5.3 pixeles", "5.4 pixeles", "5.5 pixeles", "5.6 pixeles", "5.7 pixeles", "5.8 pixeles", "5.9 pixeles", "6.0 pixeles" }));
        jPanel1.add(cboResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setText("Resolucion:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setText("Color:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        cboColor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "Negro", "Blanco", "Rojo", "Gris" }));
        jPanel1.add(cboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 120, -1));

        cboMemoria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboMemoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "2 GB", "4 GB", "8 GB", "16 GB", "32 GB", "64 GB" }));
        jPanel1.add(cboMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setText("Sistema Operativo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        cboSistemaOperativo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboSistemaOperativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Android", "IOS", "Windows Phone", "BlackBerry 6" }));
        jPanel1.add(cboSistemaOperativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 120, -1));

        cboMarca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Samsung", "Motorola", "Nokia", "Alcatel", "Sony Ericsson", "Apple", "BLU", "LG", "Huawei", "Sony", "BlackBerry", "Microsoft", " " }));
        jPanel1.add(cboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, -1));

        txtModelo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 170, -1));

        txtPrecio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 170, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpar.setBackground(new java.awt.Color(153, 255, 204));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Limpiar.png"))); // NOI18N
        btnLimpar.setText("  LIMPIAR");
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 50));

        btnModificar.setBackground(new java.awt.Color(153, 255, 204));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Modificar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 50));

        btnEliminar.setBackground(new java.awt.Color(153, 255, 204));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, 50));

        btnCancelar.setBackground(new java.awt.Color(153, 255, 204));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 50));

        btnGrabar.setBackground(new java.awt.Color(153, 255, 204));
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Grabar.png"))); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.setToolTipText("");
        btnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrabar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 50));

        btnBuscar.setBackground(new java.awt.Color(153, 255, 204));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Buscar.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 140, 450));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel10.setText("Codigo Celular:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       Statement sl;
       if((txtCodigo.getText().isEmpty())||(txtModelo.getText().isEmpty())||(txtPrecio.getText().isEmpty())){
           JOptionPane.showMessageDialog(null, "Ingresar Dato", "Error", JOptionPane.WARNING_MESSAGE);
       }else if((txtCodigo.getText().length()>20)||(txtModelo.getText().length()>20)||(txtPrecio.getText().length()>8)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
       }
       else{
        try {
            sl = com.createStatement();
            sl.execute("Insert into WILLIAM.PRODUCTO values('" + txtCodigo.getText()+ "',"
                    + "'" + cboMarca.getSelectedItem().toString() + "','"
                    + txtModelo.getText().toString() + "','"
                    + txtPrecio.getText().toString()+ "','"
                    + cboMemoria.getSelectedItem().toString()+ "','"
                    + cboResolucion.getSelectedItem().toString() + "','"
                    + cboColor.getSelectedItem().toString()+"','"
                    + cboSistemaOperativo.getSelectedItem() + "','"+Fechaderegistro2()+"')");
            JOptionPane.showMessageDialog(null, "Elemento Guradado con exito", "Guardar", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
            //Logger.getLogger(FmProductos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ESTE DATO YA EXISTE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
       }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Statement sl;
        if((txtCodigo.getText().isEmpty())||(txtModelo.getText().isEmpty())||(txtPrecio.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Ingresar Dato","Error", JOptionPane.WARNING_MESSAGE);
        }else if((txtCodigo.getText().length()>20)||(txtModelo.getText().length()>20)||(txtPrecio.getText().length()>8)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
       }else{
        try {
            sl = com.createStatement();
            String codigo=txtCodigo.getText();
            sl.execute("update WILLIAM.PRODUCTO set marca_prod='"+cboMarca.getSelectedItem().toString()+"',modelo_prod='"+txtModelo.getText().toString()+"',precio_prod='"+txtPrecio.getText()+"',memoria_prod='"+cboMemoria.getSelectedItem().toString()+"',Resolucion_prod='"+cboResolucion.getSelectedItem().toString()+"',color_prod='"+cboColor.getSelectedItem().toString()+"',sistemaoperativo_prod='"+cboSistemaOperativo.getSelectedItem().toString()+"',FechadeRegsitro_prod='"+Fechaderegistro2()+"' where codigo_prod='"+txtCodigo.getText()+"'");
            JOptionPane.showMessageDialog(null, "Elemento Modificado con exito", "Modificar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            //Logger.getLogger(FmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Statement sl;
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar Dato","Error", JOptionPane.WARNING_MESSAGE);
        }else if((txtCodigo.getText().length()>20)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
       }else{
        try {
            sl = com.createStatement();
            sl.execute("delete from WILLIAM.PRODUCTO where Codigo_prod='"+txtCodigo.getText()+"'");
            JOptionPane.showMessageDialog(null, "Elemento Eliminado con exito", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            //Logger.getLogger(FmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         dispose();        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtCodigo.setText("");
        cboMarca.setSelectedItem("----------");
        txtModelo.setText("");
        txtPrecio.setText("");
        cboMemoria.setSelectedItem("--------");
        cboResolucion.setSelectedItem("----------");
        cboColor.setSelectedItem("--------");
        cboSistemaOperativo.setSelectedItem("----------");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Statement sl=null;
        ResultSet rs=null;
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el Codigo", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                sl=com.createStatement();
                rs=sl.executeQuery("SELECT * FROM WILLIAM.PRODUCTO where codigo_prod='"+txtCodigo.getText()+"'");
                rs.next();
                cboMarca.setSelectedItem(rs.getString(2));
                txtModelo.setText(rs.getString(3));
                txtPrecio.setText(rs.getString(4));
                cboMemoria.setSelectedItem(rs.getString(5));
                cboResolucion.setSelectedItem(rs.getString(6));
                cboColor.setSelectedItem(rs.getString(7));
                cboSistemaOperativo.setSelectedItem(rs.getString(8));
                JOptionPane.showMessageDialog(null,"Busqueda Exitosa","Buscar",JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                //Logger.getLogger(FmiEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "ESTE DATO NO EXISTE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtPrecioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboColor;
    private javax.swing.JComboBox<String> cboMarca;
    private javax.swing.JComboBox<String> cboMemoria;
    private javax.swing.JComboBox<String> cboResolucion;
    private javax.swing.JComboBox<String> cboSistemaOperativo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
private String Fechaderegistro2(){
    Date d = new Date();
    DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
    String FechaIngreso = hourdateFormat.format(d);
    return FechaIngreso;
}
}
