/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedor;

import Empleados.FmListadoBDDEmpleados;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FmListadoProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FmListadoProveedor
     */
    Connection com = null;
    DefaultTableModel Proveedor = new DefaultTableModel();
    public FmListadoProveedor() {
        initComponents();
        Proveedor.addColumn("RUC");
        Proveedor.addColumn("Empresa");
        Proveedor.addColumn("Nombre");
        Proveedor.addColumn("Provincia");
        Proveedor.addColumn("Pagina Web");
        Proveedor.addColumn("Telefono");
        Proveedor.addColumn("E- mail");
        Proveedor.addColumn("Hora y Fecha de Registro");
        try {
            com=DriverManager.getConnection("jdbc:derby://localhost:1527/BDD_CeluTec","william","1234");
               
            MostrarTabla3();
            
        } catch (SQLException ex) {
            Logger.getLogger(FmListadoProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablistadoProveedor = new javax.swing.JTable();

        setClosable(true);
        setTitle("Listado Proveedor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/portapapeles.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1360, 400));

        tablistadoProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablistadoProveedor);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablistadoProveedor;
    // End of variables declaration//GEN-END:variables
 private void MostrarTabla3(){
         try {
           Statement sl = com.createStatement();
           ResultSet rs=sl.executeQuery("select * from WILLIAM.PROVEEDOR");
            while(rs.next()){ 
                String[] fila={rs.getString(1).toString(),
                    rs.getString(2).toString(),
                    rs.getString(3).toString(),
                    rs.getString(4).toString(),
                    rs.getString(5).toString(),
                    rs.getString(6).toString(),
                    rs.getString(7).toString(),
                    rs.getString(8).toString()};
            Proveedor.addRow(fila);
            tablistadoProveedor.setEnabled(false);
            }
             tablistadoProveedor.setModel(Proveedor);
             }catch (SQLException ex) {
            Logger.getLogger(FmListadoBDDEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
