/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedor;

import Empleados.FmiEmpleados;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FmProvedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FmProvedor
     */
    Connection com = null;
    public FmProvedor() {
        initComponents();
        try {
            com=DriverManager.getConnection("jdbc:derby://localhost:1527/BDD_CeluTec","william","1234");
        } catch (SQLException ex) {
            Logger.getLogger(FmProvedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPagWeb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboProvincia = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        setIconifiable(true);
        setTitle("Registro Proveedor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empresa.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(773, 410));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 10));

        btnBuscar.setBackground(new java.awt.Color(153, 255, 204));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Buscar.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar);

        btnLimpar.setBackground(new java.awt.Color(153, 255, 204));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Limpiar.png"))); // NOI18N
        btnLimpar.setText("  LIMPIAR");
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar);

        btnGrabar.setBackground(new java.awt.Color(153, 255, 204));
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Grabar.png"))); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.setToolTipText("");
        btnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrabar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGrabar);

        btnModificar.setBackground(new java.awt.Color(153, 255, 204));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Modificar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar);

        btnEliminar.setBackground(new java.awt.Color(153, 255, 204));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);

        btnCancelar.setBackground(new java.awt.Color(153, 255, 204));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 757, 68));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Registro Proveedor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos De la Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("RUC:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 40, 20));

        txtRUC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRUCKeyTyped(evt);
            }
        });
        jPanel2.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 260, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Empresa:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 20));

        txtempresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(txtempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 260, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setText("Pagina Web:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 20));

        txtPagWeb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(txtPagWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 260, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Provincia:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 20));

        cboProvincia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Azuay", "Bolívar", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "El Oro", "Esmeraldas", "Galápagos", "Guayas", "Imbabura", "Loja", "Los Ríos", "Manabí", "Morona Santiago", "Napo", "Orellana", "Pastaza", "Pichincha", "Santa Elena", "Santo Domingo de los Tsáchilas", "Sucumbíos", "Tungurahua", "Zamora Chinchipe" }));
        jPanel2.add(cboProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 220, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 370, 160));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 20));

        txtNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setText("Telefono:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        txtTefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTefonoKeyTyped(evt);
            }
        });
        jPanel4.add(txtTefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 220, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel8.setText("E-Mail:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        txtEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 240, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 350, 130));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        Statement sl;
        if((txtRUC.getText().isEmpty())||(txtempresa.getText().isEmpty())||(txtNombre.getText().isEmpty())||(txtPagWeb.getText().isEmpty())||(txtTefono.getText().isEmpty())||(txtEmail.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Ingresar Dato","Error", JOptionPane.WARNING_MESSAGE);
        }else if((txtRUC.getText().length()>13)||(txtNombre.getText().length()>70)||(txtempresa.getText().length()>70)||(txtPagWeb.getText().length()>70)||(txtTefono.getText().length()>10)||(txtEmail.getText().length()>70)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
        try {
            sl = com.createStatement();
            sl.execute("Insert into WILLIAM.PROVEEDOR values('" + txtRUC.getText().toString() + "','"
                + txtempresa.getText().toString() + "','"
                + txtNombre.getText().toString() + "','"
                + cboProvincia.getSelectedItem() + "','"
                + txtPagWeb.getText().toString() + "','"
                + txtTefono.getText().toString() + "','"
                + txtEmail.getText().toString() + "','"
                +Fechaderegistro3()+"')");
            JOptionPane.showMessageDialog(null, "Elemento Guradado con exito", "Guardar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            //Logger.getLogger(FmProvedor.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ESTE DATO YA EXISTE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Statement sl;
        if((txtRUC.getText().isEmpty())||(txtempresa.getText().isEmpty())||(txtNombre.getText().isEmpty())||(txtPagWeb.getText().isEmpty())||(txtTefono.getText().isEmpty())||(txtEmail.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "Ingresar Dato","Error", JOptionPane.WARNING_MESSAGE);
        }else if((txtRUC.getText().length()>13)||(txtNombre.getText().length()>70)||(txtempresa.getText().length()>70)||(txtPagWeb.getText().length()>70)||(txtTefono.getText().length()>10)||(txtEmail.getText().length()>70)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
        try {
            sl = com.createStatement();
            String RUC=txtRUC.getText();
            sl.execute("update WILLIAM.PROVEEDOR set empresa_prov='"+txtempresa.getText().toString()+"',Nombre_prov='"+txtNombre.getText().toString()+"',Provincia_prov='"+cboProvincia.getSelectedItem().toString()+"',PaginaWeb_prov='"+txtPagWeb.getText().toString()+"',Telefono_prov='"+txtTefono.getText().toString()+"',Email_prov='"+txtEmail.getText().toString()+"',FechadeRegistro_prov='"+Fechaderegistro3()+"' where RUC_prov='"+txtRUC.getText()+"'");
            JOptionPane.showMessageDialog(null, "Elemento Modificado con exito", "Modificar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(FmProvedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Statement sl;
        if(txtRUC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar Dato","Error", JOptionPane.WARNING_MESSAGE);
        }else{
        try {
            sl = com.createStatement();
            sl.execute("delete from WILLIAM.PROVEEDOR where RUC_prov='"+txtRUC.getText()+"'");
            JOptionPane.showMessageDialog(null, "Elemento Eliminado con exito", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(FmProvedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Statement sl=null;
        ResultSet rs=null;
        if(txtRUC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar el RUC","Error", JOptionPane.WARNING_MESSAGE);
        }else if((txtRUC.getText().length()>13)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
        try{
            sl=com.createStatement();
            rs=sl.executeQuery("SELECT * FROM WILLIAM.PROVEEDOR where RUC_prov='"+txtRUC.getText()+"'");
            rs.next();
            txtempresa.setText(rs.getString(2));
            txtNombre.setText(rs.getString(3));
            cboProvincia.setSelectedItem(rs.getString(4));
            txtPagWeb.setText(rs.getString(5));
            txtTefono.setText(rs.getString(6));
            txtEmail.setText(rs.getString(7));
        } catch (SQLException ex) {
            Logger.getLogger(FmiEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ESTE ELEMENTO NO EXISTE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtRUC.setText("");
        txtempresa.setText("");
        txtNombre.setText("");
        cboProvincia.setSelectedItem("Seleccionar");
        txtPagWeb.setText("");
        txtTefono.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtRUCKeyTyped

    private void txtTefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTefonoKeyTyped
        char c1=evt.getKeyChar();
        if(Character.isLetter(c1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtTefonoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char a=evt.getKeyChar();
        if(Character.isDigit(a)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo Letras", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtNombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPagWeb;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtTefono;
    private javax.swing.JTextField txtempresa;
    // End of variables declaration//GEN-END:variables
private String Fechaderegistro3(){
    Date d = new Date();
    DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
    String FechaIngreso = hourdateFormat.format(d);
    return FechaIngreso;
}
}
