/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventariocelutec;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FmBuscador extends javax.swing.JInternalFrame {

    /**
     * Creates new form FmBuscador
     */
    Connection com = null;
    public FmBuscador() {
        initComponents();
     ComecionBDD();
     txtver.setEditable(false);
     txtver2.setEditable(false);
     txtver3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        dbnbuscarempleados = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtver = new javax.swing.JTextArea();
        txtlimp1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtbusvarProveedor = new javax.swing.JTextField();
        dbnBusProveedor = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtver3 = new javax.swing.JTextArea();
        txtlimp2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar2 = new javax.swing.JTextField();
        dbtbuscarProducto = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtver2 = new javax.swing.JTextArea();
        txtlimp3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscador");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/busqueda.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 500));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("CEDULA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, -1));

        dbnbuscarempleados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dbnbuscarempleados.setText("Ir");
        dbnbuscarempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbnbuscarempleadosActionPerformed(evt);
            }
        });
        jPanel1.add(dbnbuscarempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 60, 20));

        txtver.setColumns(20);
        txtver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtver.setRows(5);
        jScrollPane4.setViewportView(txtver);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 340));

        txtlimp1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtlimp1.setText("Limpiar");
        txtlimp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlimp1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtlimp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 90, 20));

        jTabbedPane1.addTab("Empleados", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("RUC:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        txtbusvarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusvarProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(txtbusvarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, -1));

        dbnBusProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dbnBusProveedor.setText("Ir");
        dbnBusProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbnBusProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(dbnBusProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 60, 20));

        txtver3.setColumns(20);
        txtver3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtver3.setRows(5);
        jScrollPane5.setViewportView(txtver3);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 340));

        txtlimp2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtlimp2.setText("Limpiar");
        txtlimp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlimp2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtlimp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 90, 20));

        jTabbedPane1.addTab("Proveedor", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("CODIGO:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));
        jPanel3.add(txtBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 240, -1));

        dbtbuscarProducto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dbtbuscarProducto.setText("Ir");
        dbtbuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbtbuscarProductoActionPerformed(evt);
            }
        });
        jPanel3.add(dbtbuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 60, 20));

        txtver2.setColumns(20);
        txtver2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtver2.setRows(5);
        jScrollPane6.setViewportView(txtver2);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 340));

        txtlimp3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtlimp3.setText("Limpiar");
        txtlimp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlimp3ActionPerformed(evt);
            }
        });
        jPanel3.add(txtlimp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 90, 20));

        jTabbedPane1.addTab("Producto", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusvarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusvarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusvarProveedorActionPerformed

    private void dbnbuscarempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbnbuscarempleadosActionPerformed
     Statement sl=null;
     ResultSet rs=null;
     if(txtbuscar.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Ingresar un Valor", "Error", JOptionPane.WARNING_MESSAGE);
     }else{
     try{
         sl=com.createStatement();
         rs=sl.executeQuery("SELECT * FROM WILLIAM.EMPLEADOS where cedula_emp='"+txtbuscar.getText()+"'");
         rs.next();
         txtver.setText("Nombre: "+rs.getString(2)+"\nEStado Civil: "+rs.getString(3)+"\nGenero: "+rs.getString(4)+"\nDirecion: "+rs.getString(5)+
                 "\nTelefono de Casa: "+rs.getString(6)+"\nTelefono Celular: "+rs.getString(7)+"\nEdad: "+rs.getString(8));
          } catch (SQLException ex) {
              //Logger.getLogger(FmBuscador.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "EL DATO NO EXITE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_dbnbuscarempleadosActionPerformed

    private void dbtbuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbtbuscarProductoActionPerformed
     Statement sl=null;
     ResultSet rs=null;
     if(txtBuscar2.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Ingresar un Valor", "Error", JOptionPane.WARNING_MESSAGE);
     }else{
     try{
         sl=com.createStatement();
         rs=sl.executeQuery("SELECT * FROM WILLIAM.PRODUCTO where codigo_prod='"+txtBuscar2.getText()+"'");
         rs.next();
         txtver2.setText("\nMarca: "+rs.getString(2)+"\nModelo: "+rs.getString(3)+"\nPrecio: "+rs.getString(4)+"\nMemoria: "+rs.getString(5)+
                 "\nResolucion: "+rs.getString(6)+"\nColor: "+rs.getString(7)+"\nSistema Operativo: "+rs.getString(8));
 
          } catch (SQLException ex) {
              //Logger.getLogger(FmBuscador.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "EL DATO NO EXITE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
     }
    }//GEN-LAST:event_dbtbuscarProductoActionPerformed

    private void dbnBusProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbnBusProveedorActionPerformed
        Statement sl=null;
     ResultSet rs=null;
     if(txtbusvarProveedor.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Ingresar un Valor", "Error", JOptionPane.WARNING_MESSAGE);
     }else{
     try{
         sl=com.createStatement();
         rs=sl.executeQuery("SELECT * FROM WILLIAM.PROVEEDOR where RUC_prov='"+txtbusvarProveedor.getText()+"'");
         rs.next();
         txtver3.setText("\nEmpresa: "+rs.getString(2)+"\nNombre: "+rs.getString(3)+"\nProvincia: "+rs.getString(4)+"\nPagina Web: "+rs.getString(5)+
                 "\nTelefono: "+rs.getString(6)+"\nE-Mail: "+rs.getString(7));
          } catch (SQLException ex) {
            //Logger.getLogger(FmBuscador.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "EL DATO NO EXITE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
     }
    }//GEN-LAST:event_dbnBusProveedorActionPerformed

    private void txtlimp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlimp1ActionPerformed
        txtbuscar.setText("");
        txtver.setText("");
    }//GEN-LAST:event_txtlimp1ActionPerformed

    private void txtlimp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlimp2ActionPerformed
        txtbusvarProveedor.setText("");
        txtver2.setText("");
    }//GEN-LAST:event_txtlimp2ActionPerformed

    private void txtlimp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlimp3ActionPerformed
        txtBuscar2.setText("");
        txtver3.setText("");
    }//GEN-LAST:event_txtlimp3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dbnBusProveedor;
    private javax.swing.JButton dbnbuscarempleados;
    private javax.swing.JButton dbtbuscarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtBuscar2;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtbusvarProveedor;
    private javax.swing.JButton txtlimp1;
    private javax.swing.JButton txtlimp2;
    private javax.swing.JButton txtlimp3;
    private javax.swing.JTextArea txtver;
    private javax.swing.JTextArea txtver2;
    private javax.swing.JTextArea txtver3;
    // End of variables declaration//GEN-END:variables

   private void ComecionBDD(){
       try {
            com=DriverManager.getConnection("jdbc:derby://localhost:1527/BDD_CeluTec","william","1234");
        } catch (SQLException ex) {
            Logger.getLogger(FmBuscador.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
}
