/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empleados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FmiEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FmiEmpleados
     */
    Connection com = null;
    String genero = "";
    public FmiEmpleados() {
        initComponents();
        for (int i = 0; i <= 70; i++) {
            cboEdad.addItem("" + i);
        }
         try {
            com=DriverManager.getConnection("jdbc:derby://localhost:1527/BDD_CeluTec","william","1234");
        } catch (SQLException ex) {
            Logger.getLogger(FmListadoBDDEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboEstadoCivil = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        rdbMaculino = new javax.swing.JRadioButton();
        rdbFemenino = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDirecion = new javax.swing.JTextArea();
        txtTelefCelular = new javax.swing.JTextField();
        txtTelefCasa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cboEdad = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Registro Empleados");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/equipo.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(200, 250));
        setMinimumSize(new java.awt.Dimension(200, 250));
        setPreferredSize(new java.awt.Dimension(773, 450));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Registro Empleados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel2.setBackground(java.awt.Color.lightGray);
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Cedula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        jLabel3.setBackground(java.awt.Color.lightGray);
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Estado Civil:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel5.setBackground(java.awt.Color.lightGray);
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setText("Direcion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel6.setBackground(java.awt.Color.lightGray);
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setText("Telefono Celular:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, 20));

        jLabel7.setBackground(java.awt.Color.lightGray);
        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setText("Telefono de Casa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 20));

        jLabel9.setBackground(java.awt.Color.lightGray);
        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setText("Edad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 200, 40, 20));

        txtCedula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 170, -1));

        txtNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 230, -1));

        cboEstadoCivil.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Solter@", "Casad@", "Divorsiado@", "Viudo@", "Union Libre" }));
        jPanel1.add(cboEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 20));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        rdbMaculino.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdbMaculino);
        rdbMaculino.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        rdbMaculino.setText("Maculino");
        rdbMaculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbMaculinoMouseClicked(evt);
            }
        });
        jPanel2.add(rdbMaculino);

        rdbFemenino.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdbFemenino);
        rdbFemenino.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        rdbFemenino.setText("Femenino");
        rdbFemenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdbFemeninoMouseClicked(evt);
            }
        });
        jPanel2.add(rdbFemenino);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 300, 60));

        txtDirecion.setColumns(20);
        txtDirecion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDirecion.setRows(5);
        jScrollPane1.setViewportView(txtDirecion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 290, 100));

        txtTelefCelular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTelefCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefCelularKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 180, -1));

        txtTelefCasa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTelefCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefCasaKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 180, -1));

        jLabel13.setBackground(java.awt.Color.lightGray);
        jLabel13.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel13.setText("Años");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, 20));

        cboEdad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(cboEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 70, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 20, 10));

        btnLimpar.setBackground(new java.awt.Color(153, 255, 204));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Limpiar.png"))); // NOI18N
        btnLimpar.setText("  LIMPIAR");
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar);

        btnGrabar.setBackground(new java.awt.Color(153, 255, 204));
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Grabar.png"))); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.setToolTipText("");
        btnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrabar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel3.add(btnGrabar);

        btnModificar.setBackground(new java.awt.Color(153, 255, 204));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Modificar.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar);

        btnEliminar.setBackground(new java.awt.Color(153, 255, 204));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setPreferredSize(new java.awt.Dimension(79, 49));
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);

        btnBuscar.setBackground(new java.awt.Color(153, 255, 204));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Buscar.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar);

        btnCancelar.setBackground(new java.awt.Color(153, 255, 204));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cancelar.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 757, 68));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 423));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        Statement sl;
        if((txtCedula.getText().isEmpty())||(txtNombre.getText().isEmpty())||(txtDirecion.getText().isEmpty())||(txtTelefCelular.getText().isEmpty())||(txtTelefCasa.getText().isEmpty())||(genero.isEmpty())){
            JOptionPane.showMessageDialog(null, "Ingerse Dato", "Error", JOptionPane.WARNING_MESSAGE);
        }else if((txtCedula.getText().length()>10)||(txtNombre.getText().length()>70)||(cboEstadoCivil.getSelectedItem().toString().length()>20)||(txtDirecion.getText().length()>100)||(txtTelefCasa.getText().length()>10)||(txtTelefCelular.getText().length()>10)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
        try { 
           sl = com.createStatement();            
            sl.execute("Insert into EMPLEADOS values('" + txtCedula.getText().toString() + "',"
                    + "'" + txtNombre.getText().toString() + "','"
                    + cboEstadoCivil.getSelectedItem().toString() + "','"
                    + genero + "','"
                    + txtDirecion.getText().toString() + "','"
                    + txtTelefCelular.getText().toString() + "','"
                    + txtTelefCasa.getText().toString() + "',"
                    + Integer.parseInt(cboEdad.getSelectedItem().toString()) +",'"+Fechaderegistro()+"')");
            JOptionPane.showMessageDialog(null, "Elemento Guradado con exito", "Guardar", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {      
            //Logger.getLogger(FmiEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ESTE DATO YA ESTA REGISTRADO EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void rdbMaculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbMaculinoMouseClicked
        genero = "Masculino";
    }//GEN-LAST:event_rdbMaculinoMouseClicked

    private void rdbFemeninoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdbFemeninoMouseClicked
        genero = "Femenino";
    }//GEN-LAST:event_rdbFemeninoMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Statement sl;
        if(((txtCedula.getText().isEmpty())||txtNombre.getText().isEmpty())||(txtDirecion.getText().isEmpty())||(txtTelefCelular.getText().isEmpty())||(txtTelefCasa.getText().isEmpty())||(genero.isEmpty())){
            JOptionPane.showMessageDialog(null, "Ingresar Dato","Error", JOptionPane.WARNING_MESSAGE);
        }else if((txtCedula.getText().length()>10)||(txtNombre.getText().length()>70)||(cboEstadoCivil.getSelectedItem().toString().length()>20)||(txtDirecion.getText().length()>100)||(txtTelefCasa.getText().length()>10)||(txtTelefCelular.getText().length()>10)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
        try {
            sl = com.createStatement();
            String cedula=txtCedula.getText();
            sl.execute("update WILLIAM.EMPLEADOS set nombres_emp='"+txtNombre.getText().toString()+"',EstadoCivil_emp='"+cboEstadoCivil.getSelectedItem().toString()+"',genero_emp='"+genero+"',direcion_emp='"+txtDirecion.getText().toString()+"',telefonocasa_emp='"+txtTelefCasa.getText().toString()+"',telefonocelular_emp='"+txtTelefCelular.getText()+"',FechaRegistro='"+Fechaderegistro()+"' where cedula_emp='"+txtCedula.getText()+"'");
            JOptionPane.showMessageDialog(null, "Elemento Modificado con exito", "Modificar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            //Logger.getLogger(FmiEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       Statement sl;
       if(txtCedula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar Dato","Error", JOptionPane.WARNING_MESSAGE);
        }else{
        try {
            sl = com.createStatement();
            sl.execute("delete from WILLIAM.EMPLEADOS where Cedula_emp='"+txtCedula.getText()+"'");
            JOptionPane.showMessageDialog(null, "Elemento Eliminado con exito", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            //Logger.getLogger(FmiEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     Statement sl=null;
     ResultSet rs=null;
     if(txtCedula.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Ingrese el Numero de Cedula", "Error", JOptionPane.WARNING_MESSAGE);
     }else if((txtCedula.getText().length()>10)){
            JOptionPane.showMessageDialog(null, "Dato demasiado largo", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
     try{
         sl=com.createStatement();
         rs=sl.executeQuery("SELECT * FROM WILLIAM.EMPLEADOS where cedula_emp='"+txtCedula.getText()+"'");
         rs.next();
         txtNombre.setText(rs.getString(2));
         cboEstadoCivil.setSelectedItem(rs.getString(3));
         if(rs.getString(4).toString().equals("Masculino")){
             rdbMaculino.setSelected(true);
             genero="Masculino";
         }else{
            rdbFemenino.setSelected(true);
             genero="Femenino";
                 }
         txtDirecion.setText(rs.getString(5));
         txtTelefCasa.setText(rs.getString(6));
         txtTelefCelular.setText(rs.getString(7));
         cboEdad.setSelectedItem(rs.getString(8));
         JOptionPane.showMessageDialog(null,"Busqueda Exitosa","Buscar",JOptionPane.INFORMATION_MESSAGE);
         } catch (SQLException ex) {
            //Logger.getLogger(FmiEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ESTE DATO NO EXISTE EN LA BASE DE DATOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
     }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       txtCedula.setText("");
       txtNombre.setText("");
       cboEstadoCivil.setSelectedItem("Seleccionar");
       txtDirecion.setText("");
       txtTelefCelular.setText("");
       txtTelefCasa.setText("");
       cboEdad.setSelectedItem("0");
       genero="";
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
            
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char a=evt.getKeyChar();
        if(Character.isDigit(a)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo letras", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtTelefCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefCasaKeyTyped
        char c1=evt.getKeyChar();
        if(Character.isLetter(c1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtTelefCasaKeyTyped

    private void txtTelefCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefCelularKeyTyped
        char c2=evt.getKeyChar();
        if(Character.isLetter(c2)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            //txtCedula.setText("Ingresar solo numeros");
        }
    }//GEN-LAST:event_txtTelefCelularKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboEdad;
    private javax.swing.JComboBox<String> cboEstadoCivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMaculino;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextArea txtDirecion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefCasa;
    private javax.swing.JTextField txtTelefCelular;
    // End of variables declaration//GEN-END:variables

    
private String Fechaderegistro(){
    Date d = new Date();
    DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
    String FechaIngreso = hourdateFormat.format(d);
    return FechaIngreso;
}
}
