/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empleados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FmListadoBDDEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FmListadoBDDEmpleados
     */
    Connection com = null;
    DefaultTableModel Empleados = new DefaultTableModel();
    public FmListadoBDDEmpleados() {
        initComponents();
        Empleados.addColumn("Cedula");
        Empleados.addColumn("Nombres");
        Empleados.addColumn("Estado Civil");
        Empleados.addColumn("Genero");
        Empleados.addColumn("Direcion");
        Empleados.addColumn("Telefono");
        Empleados.addColumn("Celular");
        Empleados.addColumn("Edad");
        Empleados.addColumn("Hora y Fecha de Registro");
        
        try {
            com=DriverManager.getConnection("jdbc:derby://localhost:1527/BDD_CeluTec","william","1234");  
            MostrarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(FmListadoBDDEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoEmpleados = new javax.swing.JTable();

        setClosable(true);
        setTitle("Listado Empleados");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/portapapeles.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1360, 400));

        tblListadoEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListadoEmpleados);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblListadoEmpleados;
    // End of variables declaration//GEN-END:variables
    
    private void MostrarTabla(){
         try {
           Statement sl = com.createStatement();
           ResultSet rs=sl.executeQuery("select * from EMPLEADOS");
            while(rs.next()){ 
                String[] fila={rs.getString(1).toString(),
                    rs.getString(2).toString(),
                    rs.getString(3).toString(),
                    rs.getString(4).toString(),
                    rs.getString(5).toString(),
                    rs.getString(6).toString(),
                    rs.getString(7).toString(),
                    rs.getString(8).toString(),
                    rs.getString(9).toString()};
            Empleados.addRow(fila);
            tblListadoEmpleados.setEnabled(false);
            }
             tblListadoEmpleados.setModel(Empleados);
             }catch (SQLException ex) {
            Logger.getLogger(FmListadoBDDEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

